const ResponseMessage = {
  ADMIN_LOGGED_IN: "Admin logged in",
  INVALID_PASSWORD: "Invalid password",
  ADMIN_FETCHED: "Admin fetched",
  ADMIN_NOT_FOUND: "Admin not found",
  USER_NOT_FOUND: "User not exist",
  INTERNAL_SERVER_ERROR: "Internal server error",
  SENT_OTP: "OTP has been send to your email.",
  RESET_PASSWORD_MAIL: "Reset password OTP has been sent to your email",
  VERIFICATION_COMPLETED: "Verification completed",
  INVALID_OTP: "Invalid OTP",
  RESET_PASSWORD: "Your password has been reset",
  PASSWORD_NOT_MATCH: "Password not match",
  OLD_NEW_PASSWORD_ARE_MATCH: "Old and new password are match",
  ADMIN_UPDATED: "Admin updated",
  ADMIN_NOT_EXIST: "Admin not found",
  TOKEN_NOT_VALID: "Token not valid",
  TOKEN_NOT_AUTHORIZED: "Token not authorized",
  TOKEN_EXPIRED: "Token expired",
  USER_FETCHED: "User fetched",
  USER_FETCHED: "All Users fetched",
  USER_ADDED: "User added",
  ADMIN_ACTIVATED: "Admin activated",
  ADMIN_IN_ACTIVATED: "Admin deactivated",
  USER_LOGGED_IN: "User logged in",
  USER_NOT_FOUND: "User not found",
  USER_UPDATED: "User updated",
  USER_NOT_UPDATED: "User not updated",
  USER_ALREADY_CREATED: "User already created",
  USER_CREATED: "User created",
  USER_NOT_CREATED: "User not created",
  OLD_PASSWORD_INVALID: "Invalid old password",
  OLD_PASSWORD_SAME: "Old password are same",
  PASSWORD_CHANGED: "Password changed",
  RESET_PASSWORD_ERROR: "Reset password error",
  FIELDS_NOT_FOUND: "Fields not found",
  OLDPASSWORD_DONT_MATCH: "Old password not matched",
  PASSWORD_UPDATED_SUCCESSFULLY: "Password updated",
  USER_ALREADY_EXIST: "Email and mobile number already registered",
  EMAIL_ALREADY_EXIST: "Email already exists",
  PHONE_ALREADY_EXIST: "Mobile number already exists",
  FAILED_REGISTER_USER:
    "Something went wrong while we proceed your registration",
  FAILED_VERIFICATION:
    "Something went wrong while we proceed your verification",
  VERIFICATION_CODE_SENT:
    "Your OTP has been sent to your registered phone number and email",
  VERIFICATION_CODE_SENT_MOBILE: "Your OTP has been sent to your phone number",
  VERIFICATION_CODE_SENT_EMAIL: "Your OTP has been sent to your email",
  VERIFICATION_CODE_SENT_MOBILE_AND_EMAIL:
    "Your OTP has been sent to your phone and email",
  SOMETHING_WENT_WRONG: "Something went wrong!",
  ROLE_ADDED: "Role added",
  ROLE_UPDATED: "Role updated",
  ROLE_REMOVED: "Role removed",
  ALL_ROLE_FETCHED: "All role fetched",
  ROLE_PERMISSIONS_FETCHED: "Role and permission fetched",
  ROLE_LIST_NOT_FOUND: "Roles not found",
  ROLE_ALREADY_CREATED: "Role already created",
  CINEMA_ALREADY_CREATED: "Cinema already created",
  CINEMA_CREATED: "Cinema created",
  CINEMA_NOT_CREATED: "Cinema not created",
  REGION_ALREADY_CREATED: "Region already created",
  REGION_CREATED: "Region created",
  REGION_NOT_CREATED: "Region not created",
  REGION_UPDATED: "Region updated",
  REGION_NOT_UPDATED: "Region not updated",
  REGION_FETCHED: "Region fetched",
  REGION_NOT_FOUND: "Region not found",
  REGION_DELETED: "Region deleted",
  REGION_NOT_DELETED: "Region not deleted",
  CINEMA_FETCHED: "Cinema fetched",
  CINEMA_NOT_FETCHED: "Cinema not fetched",
  CINEMA_UPDATED: "Cinema updated",
  CINEMA_NOT_UPDATED: "Cinema not updated",
  CINEMA_ADDED: "Cinema added",
  REGION_ACTIVATED: "Region activated",
  REGION_IN_ACTIVATED: "Region deactivated",
  THIS_ACTOR_ALREADY_EXIST: "This actor already exist",
  ACTOR_UPDATED: "Actor updated",
  ACTOR_ADDED: "Actor added",
  ACTOR_REMOVED: "Actor removed",
  ACTOR_DETAILS: "Actor details",
  PROFILE_UPDATED: "Profile updated",
  MY_ACCOUNT_PROFILE_UPDATED: "Profile updated successfully",
  BAD_REQUEST: "Bad request",
  ACCOUNT_EMAIL_EXIST: "Email already exist",
  ACCOUNT_MOBILE_EXIST: "Mobile number already exist",
  MOVIESLIDER_UPDATED: "Movie slider updated",
  MOVIESLIDER_STATUS_UPDATED: "Movie slider status updated",
  MOVIESLIDER_NOT_UPDATED: "Movie slider not updated",
  MOVIESLIDER_ALREADY_CREATED: "Movie slider already created",
  MOVIESLIDER_CREATED: "Movie slider created",
  MOVIESLIDER_NOT_CREATED: "Movie slider not created",
  THIS_MOVIE_ALREADY_EXIST: "Movie already exist ",
  MOVIES_UPDATED: "Movie updated",
  MOVIES_ADDED: "Movie added",
  MOVIES_DETAILS: "Movies details",
  MOVIES_REMOVED: "Movie removed",
  MOVIES_NOT_FOUND: "Movie not found",
  SIMILAR_MOVIES_NOT_FOUND: "Similar movies not found",
  SIMILAR_MOVIES_DETAILS: "Similar movies details",
  MOVIE_SLIDER_DELETED: "Movie slider deleted",
  MOVIE_SLIDER_NOT_DELETED: "Movie slider not deleted",
  MOVIE_SLIDER_FETCHED: "Movie slider fetched",
  MOVIE_SLIDER_NOT_FOUND: "Movie slider not found",
  CMS_DETAILS_ADDED: "Cms details added",
  CMS_DETAILS_UPDATED: "Cms details updated",
  CMS_DETAILS_FETCHED: "Cms details fetched",
  THIS_CINEMA_ALREADY_EXIST: "Cinema already exist in this region",
  ERROR_IN_RETRIEVING_DATA_FROM_API: "Error in retrieving data from API",
  DATA_SYNCED_EMAIL:
    "We are running the synchronization process in the background. We will notify you via email once this process is completed.",
  CINEMA_REMOVED: "Cinema deleted",
  MOVIE_FETCHED: "Movie fetched",
  MOVIE_NOT_FETCHED: "Movie not fetched",
  NOT_RIGHTS_TO_ADD_ADMIN: "You have no rights to add admin",
  MOBILE_EMAIL_EXIST: "Mobile number or email already exist",
  SUBADMIN_CREATED: "Sub admin created",
  SUBADMIN_UPDATED: "Sub admin updated",
  SUBADMIN_REMOVED: "Sub admin removed",
  ALL_SUBADMINS: "All sub admins",
  ADMIN_ALREADY_EXISTS: "Admin Already Exists",
  ADMIN_DETAILS: "Admin details",
  FRANCHISE_LEAD_LIST_NOT_FOUND: "Franchise lead not found",
  FRANCHISE_LEAD_DETAILS_FETCHED: "Franchise lead details fetched",
  CONTACTUS_LIST_NOT_FOUND: "Contact us lead not found",
  CONTACTUS_LEAD_DETAILS_FETCHED: "Contact us lead details fetched",
  EMAIL_MOBILE_EXIST_BOTH:
    "The provided email and mobile number already exist.",
  EMAIL_EXIST: "The provided email already exists.",
  MOBILE_EXIST: "The provided mobile number already exists.",
  MOBILE_NUMBER_ALREADY_VERIFIED: "Mobile number already verified",
  EMAIL_ALREADY_VERIFIED: "Email already verified",
  THIS_NUMBER_USE_ON_ANOTHER_ACCOUNT:
    "This mobile number is already linked to another account",
  THIS_EMAIL_USE_ON_ANOTHER_ACCOUNT:
    "This email is in already linked to another account",
  TRANS_ID: "Transaction id fetched",
  ADD_SEAT_SUCCESS: "Seat added",
  SET_SEAT_SUCCESS: "Set seat successfully",
  TRANS_CANCELL: "Transaction cancelled",
  GENERAL_SETTING_UPDATED: "General settings updated",
  MOVIE_INTERESTED_REMOVED: "Movie removed from interested",
  MOVIE_INTERESTED_ADDED: "Movie added to interested",
  MOVIE_INTERESTED_LIST: "Movie interested details fetched",
  MOVIE_INTERESTED_NOT_FOUND: "Movie interested details not found",
  GENERAL_SETTING_ADDED: "General settings added",
  GENERAL_SETTING_DETAILS: "General settings details",
  THIS_CATEGORY_ALREADY_EXIST: "This gallery already exist",
  CATEGORY_UPDATED: "Gallery updated",
  CATEGORY_ADDED: "Gallery added",
  CINEMA_GALARY_DETAILS: "Cinema gallery details fetched",
  CINEMA_GALARY_IMAGE_ADDED: "Gallery image added",
  CINEMA_GALARY_IMAGE_UPDATED: "Gallery details Updated",
  ERROR_IN_RETRIEVING_DATA_FROM_API: "Error in retrieving data from API",
  STATUS_UPDATED: "Gallery status updated",
  GALLERY_DELETED: "Gallery deleted successfully",
  PRICE_LIST: "Price list",
  PRICE_NOT_FOUND: "There is no content in Price list",
  REFUND_FAILED: "Refund failed please contact admin",
  BOOKING_DETAILS: "Booking details",
  BOOKING_SESSION_EXPIRED: "Booking session expired!",
  FOOD_BVG_ORDER_LIST: "all food and beverage order list fetched",
  FOOD_BVG_ORDER_NOT_FOUND: "food and beverage order not found",
  FOOD_ITEMS_DETAILS: "Food item details fetched",
  FOOD_ITEMS_DETAILS: "Food item details fetched",
  FOOD_ITEMS_STATUS_UPDATED: "Food item status updated",
  FOOD_ITEMS_UPDATED: "Food item updated",
  GAllERY_STATUS_UPDATED: "Status updated",
  CONSSESION_ADDED: "Concession added in booking",
  SLIDER_DETAILS: "Slider details fetched",
  SLIDER_DETAILS_NOT_FOUND: "Slider details not found",
  BANNER_ADDED: "Banner added",
  BANNER_DELETED: "Banner deleted",
  BANNER_ALREADY_CREATED: "Banner already created",
  BANNER_UPDATED: "Banner updated successfully",
  BANNER_CREATED: "Banner created successfully",
  BANNER_STATUS_UPDATED: "Banner status updated",
  BANNER_DETAILS: "Banner details fetched",
  BANNER_CLICKED: "Banner clicked",
  FAILED_TO_UPDATE_BANNER_CLICK: "Failed to update banner click count",
  BANNER_NOT_FOUND: "Banner not found",
  ACCOUNT_NOT_EXIST: "No such account exists",
  DATA_SYNCED: "All data synced successfully",
  FAQ_ADDED: "FAQ added",
  FAQ_UPDATED: "FAQ updated",
  FAQ_REMOVED: "FAQ removed",
  FAQ_LIST: "FAQ list fetched",
  YOUR_REQ_SENT:
    "Your request has been sent successfully. We will contact you soon",
  USER_FETCHED: "Users fetched",
  USER_LIST_NOT_FOUND: "User list not found",
  USER_DELETED: "User deleted",
  USER_ACCOUNT_DELETED: "Account deleted successfully",
  USER_NOT_DELETED: "User not deleted",
  DETAILS_FETCHED: "Details fetched",
  ALREADY_SUBSCRIBED: "You have already subscribed.",
  SUBSCRIBED: "Successfully subscribed",
  SUBSCRIBER_LIST_FATCHED: "Subscriber list fetched",
  NEAREST_REGION_FETCHED: "Nearest region fetched",
  USER_FATCHED: "User fetched",
  TOP_DATA_FOUND: "Top data found",
  FILMCODE_REQUIRED: "Film code required",
  RATE_AND_REVIEW_RECORED: "Your review added successfully ",
  RATE_AND_REVIEW_ALREADY_ADDED: "You have already reviewed this movie",
  RATE_AND_REVIEW_IN_ACTIVATED: "Rate and review deactivated successfully",
  RATE_AND_REVIEW_ACTIVATED: "Rate and review activated successfully",
  RATE_AND_REVIEW_NOT_FOUND: "There is no rating and review given yet",
  LIST_OF_RATE_REVIEW: "Rate and review details fetched successfully",
  MOVIE_LIKED: "Your response marked as liked",
  MOVIE_DIS_LIKED: "Your response marked as Disliked",
  GOOGLE_LOGGED_IN: "Google logged in",
  GOOGLE_LOGIN_CREATED: "Google login created successfully",
  GOOGLE_LOGIN_NOT_CREATED: "Google login not created",
  TICKET_HAS_BEEN_CANCELLED:
    "Your ticket has been cancelled and refund has been initiated",
  SOCIAL_LOGGED_IN: `You are logged in through social site`,
  SOCIAL_LOGIN_CREATED: "Social login created successfully",
  SOCIAL_LOGIN_NOT_CREATED: "Social login not created",
  YOUR_REFUND_HAS_BEEN_INITIATED: "Your refund has been initiated",
  SOME_ERROR_OCCURS_WHILE_PROCCESS_YOUR_REFUND:
    "Some error occurs while we process your refund",
  CINEMA_DATA_SYNCED: "Cinema data synced successfully",
  MOVIE_IN_ACTIVATED: "Movie deactivated successfully",
  MOVIE_ACTIVATED: "Movie activated successfully",
  FEED_BACK_SAVED: "Your feedback has been recorded.",
  FEED_BACK_LIST: "Feedback list fetched successfully",
  FEED_BACK_LIST_NOT_FOUND: "There is no content found",
  ADVERTISEMENT_SAVED: "Your advertisement request has been sent.",
  ADVERTISEMENT_LIST: "Advertisement list fetched successfully",
  ADVERTISEMENT_LIST_NOT_FOUND: "There is no content found",
  OTP_EXPIRED: "OTP expired",
  INVALID_VOUCHER_CODE: "Invalid voucher code",
  VOUCHER_EXPIRED: "Voucher is expired",
  CAREER_SAVED: "Your career request has been sent",
  CAREER_LIST: "Career list fetched successfully",
  CAREER_LIST_NOT_FOUND: "There is no content found",
  TERMS_AND_CONDITION_ADDED: "Terms and conditions created successfully",
  TERMS_AND_CONDITION_UPDATED: "Terms and conditions updated successfully",
  PRIVACY_POLICY_ADDED: "Privacy policy created successfully",
  PRIVACY_POLICY_UPDATED: "Privacy policy updated successfully",
  REFUND_POLICY_ADDED: "Refund policy created successfully",
  REFUND_POLICY_UPDATED: "Refund policy updated successfully",
  ABOUT_US_ADDED: "About us details created successfully",
  ABOUT_US_UPDATED: "About us details updated successfully",
  LEGAL_NOTICE_ADDED: "Legal notice created successfully",
  LEGAL_NOTICE_UPDATED: "Legal notice updated successfully",
  ADMIN_PARTNER_CREATED: "Partner Created Successfully",
  ADMIN_PARTNER_NOT_CREATED: "Unable to create partner",
  ADMIN_PARTNER_UPDATED: "Partner updated Successfully",
  ADMIN_PARTNER_NOT_UPDATED: "Partner Details not updated",
  PARTENER_EXIST: "Partner already exists",
  ADMIN_PARTNER_LIST_GET: "Partner List Fetch",
  ADMIN_PARTNER_STATUS_VALUE:
    "Invalid value for isActive. It must be a boolean.",
  ADMIN_PARTNER_NOT_FOUND: "Partner not found",
  ADMIN_PARTNER_STATUS_UPDATED: "Partner status changed successfully",
  ADMIN_PARTNER_DELETE_NOT_FOUND: "Partner not found",
  ADMIN_PARTNER_DELETE: "Partner deleted successfully",
  USER_LOGOUT: "User logout successfully",
  USER_FCM_TOKEN_UPDATED: "FCM token updated successfully",
  NOTIFICATION_STATUS_CHANGE: "Notification status change successfully",
  ALL_USER_NOTIFICATION: "User all notification",
  USER_STATUS_ADDED: "User status added successfully",
  USER_STATUS_UPDATED: "User status updated",
  USER_STATUS_NOT_UPDATED: "User status not updated",
  USER_STATUS_GETED: "User status fetch",
  USER_STATUS_NOT_ADDED: "User status not added",
  PAYMENT_DETAILS: "Payment details fetched successfully",
  BOOKING_DETAILS_MISMATCH: "Booking details mismatched",
  DATA_SYNCED: "All data synced successfully",
  INVALID_TYPE: "Invalid type provided",
  CINEMA_DETAILS: "Cinema details fetched successfully",
  LICENCE_CODE_UPDATED: "License has been updated successfully",
  VOUCHER_APPLIED: "Coupon applied successfully",
  GROUP_BOOKING_DETAILS_ADDED: "Group booking Details added successfully",
  GROUP_BOOKING_DETAILS_NOT_FOUND: "Group booking Details not found",
  GROUP_BOOKING_DETAILS_FETCHED: "Group booking Details fetched successfully",
  INFLUENCER_DETAILS_ADDED: "Influencer Details added successfully",
  INFLUENCER_DETAILS_NOT_FOUND: "Influencer Details not found",
  INFLUENCER_DETAILS_FETCHED: "Influencer Details fetched successfully",
  CINEMA_NOT_FOUND: "Cinema Not Found",
  CINEMA_ACTIVE: "Cinema active successfully",
  CINEMA_DEACTIVE: "Cinema deactive successfully",
  BLOGS_DETAILS: "Blogs details fetched",
  THIS_BLOGS_ALREADY_EXIST: "Blog already exist",
  BLOGS_ADDED: "Blog added successfully",
  BLOGS_UPDATED: "Blog updated successfully",
  BLOG_DETAILS: "Blogs details",
  BLOGS_DELETED: "Blog deleted successfully",
  BLOGS_STATUS: "Blog status updated",
  BLOGS_NOT_FOUND: "Blog not found",
  BG_BLOGS_ALREADY_EXIST: "Background Blog already exist",
  BG_GALLARY_ADDED: "Gallary background added successfully",
  BG_GALLARY_UPDATED: "Gallary background updated successfully",
  BG_GALLARY_NOT_FOUND: "Gallary background not found",
  BG_GALLARY_ALREADY_EXIST: "Background Gallary already exist",
  MEMBERSHIP1_NOT_FOUND: "MemberShip1 not found",
  MEMBERSHIP1_ALREADY_EXIST: "MemberShip1 is already exist",
  MEMBERSHIP1_ADDED: "Membership1 added successfully",
  MEMBERSHIP1_UPDATED: "Membership1 updated successfully",
  MEMBERSHIP1_DETAILS: "Membership1 details fetched successfully",
  MEMBERSHIP1_NOT_UPDATED: "Membership1 details not updated",
  MEMBERSHIP1_STATUS_UPDATED: "Membership1 status updated successfully",
  MEMBERSHIP1_DELETED: "Membership1 deleted successfully",
  REPORT_AND_ISSUE_SENT: "Issue reported",
  REPORT_ISSUE_LIST_FETCHED: " Report issue fetch successfully",
  COUPON_CREATED: "Coupon created successfully",
  COUPON_UPDATE: "Coupon updated successfully",
  COUPON_LIST_NOT_FOUND: "Coupons not available",
  COUPON_LIST: "Coupon list fetched successfully",
  COUPON_DELETE: "Coupon deleted successfully",
  COUPON_STATUS_UPDATED: "Coupon status updated successfully",
  COUPON_NOT_FOUND: "Coupon not available",
  COUPON_ACTIVE_SUCCESS: "Coupon activated successfully",
  COUPON_DEACTIVE_SUCCESS: "Coupon deactivated successfully",
  SUBSCRIPTION_NOT_FOUND: "Subscription not available",
  SUBSCRIPTION_UPDATED: "Subscription updated successfully",
  SUBSCRIPTION_ADDED: "Subscription created successfully",
  SUBSCRIPTION_LIST: "Subscription list fetched successfully",
  SUBSCRIPTION_DELETED: "Subscription deleted successfully",
  SUBSCRIPTION_ACTIVE_SUCCESS: "Subscription activated successfully",
  SUBSCRIPTION_DEACTIVE_SUCCESS: "Subscription deactivated successfully",
  SUBSCRIPTION_TITLE_ALREADY_EXISTS: "Subscription title already exists",
  INVALID_PERIOD: "Invalid date format provided",
  TRANSACTION_LIST_FETCHED: "Transaction list fetched successfully",
  NO_TRANSACTIONS_FOUND: "No transactions found",
  USER_DETAILS_FETCHED: "User details fetched",
  MEMBERSHIP_NOT_FOUND: "Membership not found",
  MEMBERSHIP_DETAILS_FETCHED: "Membership details fetched successfully",
  MEMBERSHIP_UPDATED: "Membership details updated successfully",
  MEMBERSHIP_DELETED: "Membership deleted successfully",
  MEMBERSHIP_ADDED: "Membership added successfully",
  MEMBERSHIP_FOUND: "Membership found",
  NOT_MEMBERSHIP_PUARCHASED: "Membership not purchased",
  ITEM_SEQUENCE_ALREADY_EXIST: "Item sequence already exist",
  CONTACT_US_NOT_FOUND: "Contact Us not found",
  CONTACT_US_UPDATED: "Advertise with updated successfully",
  CONTACT_US_ADDED: "Advertise with Us added successfully",
  ADVERTISE_DELETED: "Advertise deleted successfully",
  CAREER_NOT_FOUND: "Career with us not found",
  CAREER_US_UPDATED: "Career with us updated successfully",
  CAREER_US_ADDED: "Career with Us added successfully",
  CAREER_DELETED: "Career deleted successfully",
  MEMBERSHIP_DETAILS: "Memership fetch successfully",
  ADVERTISEMENT_DETAILS: "Advertisement fetch successfully",
  CAREER_DETAILS: "Career fetch successfully",
  ADVERTISEMENT_NOT_FOUND: "Advertisement not found",
  CAREER_NOT_FOUND: "Career not found",
  COUPONS_FETCHED: "Coupon fetched successfully",
  COUPON_TITLE_ALREADY_EXISTS: "Coupon name already exists",
  LIST_FETCH: "List fetch successfully",
  COUPON_NOT_VALID: "Coupon not valid!",
  COUPON_APPLIED: "Coupon applied successfully",
  CINEMA_SHOW_COUNT_FETCHED: "Cinema show counts fetched",
  SHOW_NOT_AVAILABLE:
    "These show are no longer available yet. Please try another show",
  MOVIE_NO_LONGER_AVAILABLE: "This movie is no longer available",
  LOGIN_ACTIVITY_FETCHED: "Admin login activity details fetched",
  BOOKING_DISABLED: "Booking is disable for sometime.",
  WELCOME_GIFT_NOT_FOUND: "Welcome gift not found.",
  WELCOME_GIFT_FETCHED: "Welcome gift fetched successfully.",
  WELCOME_GIFT_MARKED_RECEIVED: "Welcome gift mark as received successfully.",
  WELCOME_GIFT_ALREADY_RECEIVED: "Welcome gift already received.",
  WELCOME_GIFT_NOT_RECEIVED: "Welcome gift not received.",
  COUPON_REMOVED: "Coupon removed successfully.",
  FEE_ACTIVITY_LOG_UPDATED: "Fee updated successfully.",
  GLOBAL_CONVIENT_FEE_FETCHED: "Global convience fee log fetched successfully.",

  SUBSCRIPTION_REQUEST_ALREADY_EXISTS:
    "Subscription update request already exists.",
  SUBSCRIPTION_REQUEST_CREATED: "Subscription request created successfully.",
  SUBSCRIPTION_REQUEST_UPDATED: "Subscription request updated successfully.",
  SUBSCRIPTION_REQUEST_NOT_FOUND: "Subscription request not found.",
  SUBSCRIPTION_REQUEST_DELETED: "Subscription request deleted successfully.",
  SUBSCRIPTION_REQUEST_LIST_FETCHED:
    "Subscription request list fetched successfully.",
  NO_SUBSCRIPTION_REQUESTS_FOUND: "No subscription requests found.",
  SUBSCRIPTION_REQUEST_FETCHED: "Subscription request fetched successfully.",
  SUBSCRIPTION_REQUEST_STATUS_UPDATED:
    "Subscription request status updated successfully.",
  SUBSCRIPTION_REQUEST_ALREADY_PROCESSED:
    "Subscription request already processed.",
  SUBSCRIPTION_LIMIT_REACHED:
    "Only three subscrptions can be active at a time.",
  GLOBAL_NOTIFICATION_NOT_FOUND: "Global notification not found.",
  GLOBAL_NOTIFICATION_STATUS_UPDATED:
    "Global notification status updated successfully.",
  GLOBAL_NOTIFICATION_CANNOT_UPDATE:
    "The notification has already been sent and cannot be updated.",
  MEMBERSHIP_TERMS_UPDATED:
    "Membership terms and conditions have been successfully updated.",
  MEMBERSHIP_TERMS_ADDED:
    "New membership terms and conditions have been successfully added.",
  FRANCHISE_LOCATION_EXIST:
    "An application already exists for this franchise location using this email.",
  REWARD_CONFIG_SAVED: "Reward configuration saved successfully.",
  REWARD_CONFIG_FETCHED: "Reward configuration fetched successfully.",
  REWARD_CONFIG_NOT_FOUND: "Reward configuration not found.",
  COINS_REDEEMED: "Coins redeemed successfully.",
  INSUFFICIENT_COINS: "Insufficient coin balance.",
  REDEMPTION_CAP_EXCEEDED: "Redemption amount exceeds the maximum cap.",
};

export default ResponseMessage;
