name: connplex-backend

on:
  push:
    branches: [development]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: '194.233.77.156'
          username: 'root'
          key: ${{ secrets.SSHKEY }}
          script: sh /root/connplex_backend.sh
